### ISSUE TITLE
Not working if keyboard shortcut is used to submit

### ISSUE THREAD

**Issue by dipta007** [raphaelheinz/LeetHub-3.0#16] opened 2024-01-07 02:16 UTC
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When the problem is submitted through keyboard shortcut `cmd + enter`, the extension doesn't work.

**Describe alternatives you've considered**
If submitted using click, it works.

**Additional context**
I can open a PR if you are busy.

**Comment by raphaelheinz** [comment] 2024-01-07 13:58
Hi @dipta007,
thanks for reporting this issue. Unfortunately I cannot reproduce it because the shortcut works on my laptop since v0.0.5 (Related PR:  #10).  Could you try to reproduce?

One limitation is that you have to wait 4 seconds before entering new characters, which is not ideal, but I haven't found a better solution in a hurry. I would very much welcome your contribution. Feel free to open a PR :) I will merge it and update the plugin.

**Comment by dipta007** [comment] 2024-01-07 23:08
@raphaelheinz I just checked with 2 of my accounts and I found out that in my premium account its not working but its working on a non-premium account. Is it the same case for you? I tried to console.log the `textarea` in line no 1059 in `leetcode.js` and found this in the console tab.

![image](https://github.com/raphaelheinz/LeetHub-3.0/assets/13894030/bd796b72-6f58-4fc5-9e98-1c28ef53ee56)

When I tried to reveal the element that was logged I got this error:

`Node cannot be found in the current page.`

Till now, I have no idea why that happens with premium account and not with non-premium, but I have a hunch that is because of the debugger availability in premium account. Let me know what you think. Thanks for such a great extension.

**Comment by dipta007** [comment] 2024-01-08 00:16
Adding this code block works in most (~98%) of the cases. It fails when the dom takes more than 2 seconds to load.

```js
setTimeout(() => {
  observer.observe(document.body, {
    childList: true,
    subtree: true,
  });
}, 2000);
```

I couldn't find any specific event listener/function that will execute after the whole dom is loaded.

**Comment by raphaelheinz** [comment] 2024-01-08 21:53
Many thanks for your investigation!
Unfortunately, I cannot currently test with a Premium account. 

I think you are on the right track. Maybe the debugger is adding an additional textarea element that conflics with the indices of the hardcoded conditions below. I'm not sure though.

https://github.com/raphaelheinz/LeetHub-3.0/blob/d7f813cf7bfc03831586563f674143cc551ccf02/scripts/leetcode.js#L1056-L1057

In the meantime, until we find a better idea, I would suggest integrating your fix into the current build so that it at least works in most cases.

**Comment by raphaelheinz** [comment] 2024-02-07 11:47
I added this issue to "Roadmap" page in our wiki. For now, I am closing this issue as it is not critical..

**Closed by raphaelheinz** 2024-02-07 11:47 UTC
